name: Descarga
# Controls when the workflow will run
on:

  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * 6'
  #  At 00:00 on Saturday

jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Parte 1"
    - name: Run test1 script
      run: python test.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /
        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
        push_options: '--force'

  test2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Parte 2"
    - name: Run test1 script
      run: python test2.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /
        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
        push_options: '--force'

  test3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Parte 3"
    - name: Run test1 script
      run: python test3.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /
        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
        push_options: '--force'

  test4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Parte 4"
    - name: Run test1 script
      run: python test4.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /
        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
        push_options: '--force'

  test5:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "Parte 5"
    - name: Run test1 script
      run: python test5.py

    - uses: stefanzweifel/git-auto-commit-action@v2
      with:
        commit_message: "Actualizacion"
        branch: main
        # Optional glob pattern of files which should be added to the commit
        #file_pattern: /
        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: Actions Bot
        commit_user_email: lmonsalve22@gmail.com
        commit_author: DataIntelligence BOT <lmonsalve22@gmail.com>
        push_options: '--force'